name: 更新 nezha agent 二进制文件

on:
  workflow_dispatch: # 手动触发工作流
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update_release:
    name: 下载并上传 release
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO: nezhahq/agent
      DOWNLOAD_FILE: nezha-agent_freebsd_arm64.zip
      RENAMED_FILE: nezha_agent_arm64
      TARGET_TAG: arm64
      UPLOAD_REPO: yutian81/serv00-ct8-ssh

    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: 下载 release 文件
        run: |
          curl -sL https://github.com/${{ env.SOURCE_REPO }}/releases/latest/download/${{ env.DOWNLOAD_FILE }} -o ${{ env.DOWNLOAD_FILE }}
          unzip -o ${{ env.DOWNLOAD_FILE }}

      - name: 重命名解压文件
        run: |
          mv ${{ env.DOWNLOAD_FILE }} ${{ env.RENAMED_FILE }}

      - name: 检查 release 是否已存在
        id: check_release
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ env.UPLOAD_REPO }}/releases/tags/${{ env.TARGET_TAG }})
          echo "RESPONSE=$RESPONSE"
          release_exists=$(echo $RESPONSE | jq -r '.message' | grep -c 'Not Found')
          echo "release_exists=$release_exists" >> $GITHUB_ENV

      - name: 如果 release 不存在，则创建新的 release
        id: create_release
        if: ${{ env.release_exists == '1' }}
        run: |
          RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
                  "tag_name": "${{ env.TARGET_TAG }}",
                  "name": "Release ${{ env.TARGET_TAG }}",
                  "body": "Release for ${{ env.TARGET_TAG }} architecture",
                  "draft": false,
                  "prerelease": false
                }' \
            https://api.github.com/repos/${{ env.UPLOAD_REPO }}/releases)
          echo "创建 release: $RESPONSE"
          upload_url=$(echo $RESPONSE | jq -r '.upload_url' | sed 's/{?name,label}//')
          echo "upload_url=$upload_url" >> $GITHUB_ENV

      - name: 删除现有资产（如果存在）
        id: delete_existing_asset
        if: ${{ env.release_exists == '0' }}
        run: |
          ASSET_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ env.UPLOAD_REPO }}/releases/tags/${{ env.TARGET_TAG }} | \
            jq -r --arg renamed_file "${{ env.RENAMED_FILE }}" '.assets[] | select(.name == $renamed_file) | .id')
          if [ "$ASSET_ID" != "null" ]; then
            echo "删除现有的资产，ID: $ASSET_ID"
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ env.UPLOAD_REPO }}/releases/assets/$ASSET_ID
          fi

      - name: 上传新的资产到 release
        run: |
          upload_url="${{ env.upload_url }}"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @./${{ env.RENAMED_FILE }} \
            "${upload_url}?name=${{ env.RENAMED_FILE }}"
